apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-kustomize
spec:
  selector:
    matchLabels:
      app: myapp-kustomize
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-kustomize
    spec:
      containers:
      - name: myapp-kustomize
        image: nginx
        ports:
        - containerPort: 8080